### ISSUE TITLE
Replace non-OHM borders with OHM borders at zoom < 6

### ISSUE THREAD

**Issue by jeffreyameyer** [Open-Historical-Map-Labs/openhistoricaltiles#16]
Right now, we're currently seeing modern boundaries at zoom < 6.

As a user, I would like to eventually see the borders only for whatever time we select, and I'd like to be able to select a time for any zoom. 

So, at any zoom, the only borders that should be rendered should be:
- in OHM
- relevant for whatever time is selected (later work)

**Comment by danrademacher** [comment]
Boiling that down a little:

- [x] Remove ALL NE admin/state boundaries
- [x] Persist OHM boundaries at z1-5. Do we need more specificity here? Like Admin0? Not sure what tagging is like on these.

Example of OHM boundary to show at lower zooms is in Italy:
https://openhistoricalmap.github.io/openhistoricaltiles/prettymap/#6.39/39.88305/16.74211/

**Comment by gregallensworth** [comment]
Here we go:

https://openhistoricalmap.github.io/openhistoricaltiles/prettymap/#3.00/52.20910/3.01754/

https://openhistoricalmap.github.io/openhistoricaltiles/prettymap/#2.00/47.95343/-82.03029/
