### ISSUE TITLE
Crib a Tangram style as basemap

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#18]
We know we want to make a general purpose Tangram style for two reasons:
1. Better underlayment for the Date Issues map (https://openhistoricalmap.github.io/openhistoricaltiles/dateerrors/#14/40.7721/-119.2137)
2. Better future use for a date filter slider

We know lots of people who worked on these. And the endpoints on this page provide the style files:
https://www.nextzen.org/

Live previews:
https://tangrams.github.io/cinnabar-style
https://tangrams.github.io/refill-style
https://tangrams.github.io/tron-style
https://tangrams.github.io/walkabout-style

Based on that, I would say Cinnabar is best starting point:
![image](https://user-images.githubusercontent.com/1423200/44490507-5bd3d980-a613-11e8-8c7f-50d24614950f.png)

Typical "map" colors, no relief, nothing too fancy.

style files:
https://www.nextzen.org/carto/cinnabar-style/9/cinnabar-style.zip

**Comment by danrademacher** [comment]
Seems like we might want to find a time when @mojodna is available to consult on this, since we've never worked with full scale Tangram styles

**Comment by gregallensworth** [comment]
ffad440 -- Refactored the basemap into a separate `L.tileLayer` instance, so the `VLAYER` Tangram vectile layer is 100% separate. Renamed `scene.yaml` to `scene-dateerrors.yaml` to "make room" for there being more than one.

**Comment by gregallensworth** [comment]
The goal here was to rework the **dateerrors** map, so as to use OHM as a basemap and overlay the OHM-errors. We may want to shelve this though, as that goal is achieved in #3 with Mapbox GL technology.

**Comment by danrademacher** [comment]
Closing this out given Mapbox GL progress on #3
