### ISSUE TITLE
URL params on dateissue map don't load map to expected location

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#25]
During Slack discussion Gregor said:
> https://openhistoricalmap.github.io/openhistoricaltiles/dateissues/#11.89/50.36570/2.81261/
> That’s that area near Givenchy. I see that everything has bad dates and nothing had properly formatted dates, so expect the map to be blank.

I clicked that link expecting it to load a location in France, zoomed in at z11.89. 

Instead, I get default center on mainland US:
![image](https://user-images.githubusercontent.com/1423200/45458061-c2926300-b6a6-11e8-82e9-423c2ca15b97.png)

This is the same view as if I load https://openhistoricalmap.github.io/openhistoricaltiles/dateissues/ , which leads me to suspect that URL has is not parsed on pageload

**Comment by gregallensworth** [comment]
Fixed and deployed.
