### ISSUE TITLE
New combined map of date issues + date filtering

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#29]
Our larger goal here, is a combined OHM map that could ultimately act as the front-page map of www.openhistoricalmap.org At its base this could be a merge/mashup of the `dateissues` and `datefilter` maps, with a few additional behaviors.

Reference:

http://www.openhistoricalmap.org/

https://openhistoricalmap.github.io/openhistoricaltiles/datefilter/#14.00/40.76861/-119.23122/2009-08-15,2009-09-15/

https://openhistoricalmap.github.io/openhistoricaltiles/dateissues/#14.00/40.77159/-119.21816/

- [x] new MBGL map, with date filter for features in which dates are good

- [x] behavior: click feature, get info

- [x] control: layer switcher, toggles a date issues behavior for those with invalid/missing dates (panel listing features + orange/red features on map)

- [x] behavior: click feature, get info for bad-date items

- [x] layer switcher should also allow for picking a real basemap for reference. Maybe OSM?

- [x] control: geocoder address search and zoom

- [x] control: geolocation zoom

- [x] control: welcome modal

- [ ] layer control: Map Notes  *This may require some CORS-related work first* as it's on a different URL origin, so we can access the endpoints over at www.openhistoricalmap.org

- [ ] map control: Add Note, adds a temporary marker to the center of the map and opens a tool for posting to OHM endpoint where a note is placed onto the map (then refresh the layer?)

- [ ] improve styling & cosmetics somewhat, working with Tim

**Comment by gregallensworth** [comment]
Layer control example:

![image](https://user-images.githubusercontent.com/3117633/46752823-06ab6000-cc73-11e8-940a-7d53a13653b3.png)

This allows for references basemaps and label overlays to be toggled. Folks can't draw and edit shapes in a vacuum and will need to refer to modern reference points.

**Comment by gregallensworth** [comment]
Mockup of possible new layout:

![image](https://user-images.githubusercontent.com/3117633/52590685-d0cfe100-2df6-11e9-9fb5-6bba67973d3f.png)


- [ ] Rework of the geocoder tool and the geolocation button, into a new combined UI at top-left.
- [ ] Rework of date filter as a single-value entry, and as a slider.
  * Means adjusting the math for matching features to this point date. Current math is a date range.
- [ ] Manual date entry widget, and When Am I functionality, top-left.

**Comment by danrademacher** [comment]
Replaced by #33
