### ISSUE TITLE
Diffs consumption re boundaries

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#30]
Expanding on the work done in #13 in regards to boundaries...

We've been following the openmaptiles method, in which boundaries are loaded. This is less than optimally, as it takes a half-hour to tun and is "just a second thing" Ideally, we would modify the `mapping.yaml` so that the boundaries were imported via imposm3 like everything else.

See what we can do about this. Ideal targets would include:

- [ ] remove the ohmborders tasks and documentation, as they would not be used anymore

- [ ] adjust the `mapping.yaml` to import boundaries. refer to the ohmborder source code to find the filtering and features

- [ ] purge the DB and reload, confirm presence of boundaries

- [ ] make some boundary-related change to OHM data, watch it propagate into vector tiles in our usual timeframe

**Comment by danrademacher** [comment]
Shifting temporarily to @jeffreyameyer so he can include thoughts and sketch on a broader solution to the low zoom border problem.

**Comment by danrademacher** [comment]
I[;m going to close this out and make a new issue based on latest approach
