### ISSUE TITLE
Blank dates: Missing data or eternal features?

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#32]
Pulling this out into an issue:
>e.g. for the blank start or end dates, I'd like to treat those as data entry omissions. For dawn of time / present day, how badly would things break if we used a wildcard, like '*'?

Seems like two concerns here:
* What can we accommodate in the timeline slider/date filter? What's the lest hack way here?
* What do OHM editors/contributors think about a wildcard? 

If we're going to use an arbitrary string, I suspect we'd want something other that an asterisk, which seems likely to get mistaken for an actual wildcard.

This will also be relevant to https://github.com/OpenHistoricalMap/openhistoricalmap-docker/issues/2 -- if we implement a date picker there to help with data formatting, how do we also allow someone to enter whatever thing means "eternal"?

**Comment by danrademacher** [comment]
`e` for eternal?

**Comment by danrademacher** [comment]
or `a` and `o` for omega?

**Comment by gregallensworth** [comment]
Per issue #41 the current implementation of the timeslider treats "" as the start/end of time, e.g. "since prehistory" or "through the current day and the foreseeable future"
