### ISSUE TITLE
New Borders data process: planning issue

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#35]
Here's what we said in latest scope:

> The current approach uses the same method as OSM, consuming borders from Natural Earth as a totally separate, nondiffed process. It would be much better to draw borders directly form OHM, since these are likely to be a main element of interest to OHM mappers. Here's the approach:
> 1. Create IMPOSM 3 mapping for borders including generalization
> 2. Modify OpenHIstoricalTiles vectiles schema to ingest borders
> 3. Use those in carto display, dealing with double overlap borders, so hard to use dashed lines, so skip those
> 4. Remove the OSM-borders tool

Seth do you think these are specific enough that we can just treat 1-4 as distinct issues, or should we break down further?

**Comment by sethfitz** [comment]
Yes, 4 distinct issues sounds right to me, in that order, too.

**Comment by danrademacher** [comment]
Ok, those are made! 47 and 48 I wasn't super sure if those should be yours or Gregors, so left them unassigned for now. Can go whichever way makes most sense.

**Comment by sethfitz** [comment]
Sounds good, thanks!!
