### ISSUE TITLE
Minor change in Plus/minus buttons, lose home, underline dates

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#36]
Now that we have the timeline live and working, Tim and I agreed that Plus/Minus/Home don't make a lot of sense where we have them, and Home not at all.

Let's change this around like this instead:

![image](https://user-images.githubusercontent.com/1423200/56935048-9562bb80-6aa3-11e9-9479-bcd2b21e1d52.png)

Seems pretty clear, then once done I'll send it out to the OHM community list for wider feedback

**Comment by danrademacher** [comment]
Probably we should also make the Current year font size at least as large as the two ends.

**Comment by gregallensworth** [comment]
This is expanding on #33 in which an example page was built, which uses a new MBGL TimeSlider control.

**Comment by gregallensworth** [comment]
Done. Looks sharp.

https://openhistoricalmap.github.io/openhistoricaltiles/mbgl-control-timeslider/demo/
