### ISSUE TITLE
TimeSlider demo, Change OHM map style

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#39]
Expanding on the MBGL TimeSlider control demonstration, built in #33 

Jeff said via email: "the style for the prototype map doesn't look the same as the existing style on OHM. We'll be working on making some changes to it"

I need to get specifics from Jeff as to where they have implemented a new vector tile style, so I can merge/copy that new style into the two TimeSlider demos (MBGL and Leaflet-MBGL)

- [ ] confirm with Jeff which map style the demos should be using; if the comparison is to some raster tiles, then we may need to create a new Issue with Tim as to cartography and implementing the target look in vector tile styles.

- [ ] Adapt style into the MBGL Control demo

- [ ] Adapt style into the Leaflet-over-MBGL demo

┆Created By: Dan Rademacher

**Comment by danrademacher** [comment]
To be clear, making a new map style, which Tim and Stephen started, has been deprioritized until after both timeslider and borders work

**Comment by danrademacher** [comment]
I'm going to close this out -- the work here is not so much "use the correct style" but rather iteratively develop the style we're using until it meets OHM needs. That's more than one issue and likely most work will be in Maputnik with occasional updates to the style on timeslider demo and staging site. That's captured in other issues with labels `cartography` and `stylesheet`
