### ISSUE TITLE
No data for 2018-2019 ?

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#41]
New York City, 2017. Move time forward into 2018 or 2019, and there's suddenly nothing visible.

http://localhost:9000/demo/#14.600/40.80623/-73.91894/2017,0-2019

https://openhistoricalmap.github.io/openhistoricaltiles/mbgl-control-timeslider/demo/#14.629/40.81577/-73.91392/2017,0-2019

May be a data issue, may be a computer bug, may be a hole in our whole logic for how to think of date filtering. Figure out what, so we can plan next steps.

**Comment by gregallensworth** [comment]
First note: Data issues. These buildings have explicit end dates of _2018-11-01_ Therefore it is correct that they vanish in 2019. But shouldn't they persist through 2018?

![image](https://user-images.githubusercontent.com/3117633/57042553-d977cc80-6c19-11e9-8741-7a2ac1c012f5.png)

Also, notice the orange features in the map. These all have a _blank_ starting date, and an end date of _2018-11-10_ We never did define the expected behavior for items which have a start and no end, or an end but no start. Maybe best to treat "" as the beginning/end of time, e.g. "prehistory through 1923" or "since 1776 through present date"


- [x] Adjust filters to handle "" values as being beginning/end of time.

- [x] Check filter logic re _2018-11-01_ not fitting a year selection of _2011_

**Comment by gregallensworth** [comment]
49a3867 Filtering adjusted, so "" values are start/end of time ("prehistory", "current date and expected future")

This brings in several features which have a blank start date, and therefore had previously been missed:

![image](https://user-images.githubusercontent.com/3117633/57042969-10021700-6c1b-11e9-80d1-8f31170671db.png)

Of course, this also means that these features are now displayed back into prehistory, such as in this screenshot from the year 100 CE:

![image](https://user-images.githubusercontent.com/3117633/57043657-15606100-6c1d-11e9-82a6-57b2690f0c0c.png)

**Comment by gregallensworth** [comment]
5bfbce6 adjusts the filtering logic to _include_ features which started/ended within the selected calendar year. Thus, those buildings in NYC will show when 2018 is selected, as they did have a presence during some part of 2018.

**Comment by jeffreyameyer** [comment]
Could be a data issue. I'll fix any underlying data. Would be better if we
could figure out an approach / wildcard for "current day / present"
