### ISSUE TITLE
Time Slider: There is no year 0

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#44]
In the Gregorian calendar there is no year 0.
* Dates skip directly from -0001-12-31 to 0001-01-01
* The delta between June 30 +1 and June 30 -1 is not 2 years, but 1 year.

For UI purposes, this is an Interesting quirk, since `input[type-"range"]` form controls do not allow for individual values being skipped. It may be necessary to write something new completely from scratch.

┆Created By: Dan Rademacher

**Comment by danrademacher** [comment]
Seems like we've adapted to this OK for now. Closing out until there's a clear need to address this date problem.
