### ISSUE TITLE
Last changes?

### ISSUE THREAD

**Issue by daelba** [Open-Historical-Map-Labs/openhistoricaltiles#53]
Demo slider ceased to reflect changes, which I have made since yesterday. For example, see this changeset: http://www.openhistoricalmap.org/changeset/5557, which should be rendered there: https://openhistoricalmap.github.io/openhistoricaltiles/mbgl-control-timeslider/demo/#17.551/49.54770/17.73003/1910,1890-1970. Is it intended or bug?

**Comment by danrademacher** [comment]
Based on changes in #56 I think we have this changeset now.

Xray view
https://vtiles.openhistoricalmap.org/#18/49.54759/17.72888

Staging
http://openhistoricalmap-1936150974.us-east-1.elb.amazonaws.com/#map=18/49.54793/17.72911&layers=O

![image](https://user-images.githubusercontent.com/1423200/64227424-46d18d80-ce98-11e9-9939-375fc1b18766.png)

**Comment by daelba** [comment]
Great, thanks.
