### ISSUE TITLE
Finalize approach for OHM MBGL js location

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#62]
See discussion here:

https://greeninfo.slack.com/archives/CAA31JATU/p1567817184074400

gh-pagws branch of `openhistoricaltiles` or new repo?

┆Created By: Dan Rademacher
┆Due Date: 2019-09-09

**Comment by danrademacher** [comment]
Going with the GH PAges approach, see #61

**Comment by jeffreyameyer** [comment]
FYI - when I click on the slack link, I get an error.

Not sure I follow what the hosting tradeoffs were, as it references repos, as opposed to hosting... is this just for the code?

**Comment by danrademacher** [comment]
Nothing needed here. Details in #61. I posted this here accidentally -- just a poorly named internal task that got filed here after I set up some syncing of an internal Asana task list with this repo, so that we don't miss future new issues here once we get into map styling.
