### ISSUE TITLE
review rendering issues >z9

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#66]
Pulled from #65 
 area Jeff saw as a problem seems to be only when zoom is >=10
This works:
https://openhistoricalmap.github.io/openhistoricaltiles/leaflet-control-mbgltimeslider/demo/#9.000/50.31039/2.59689/1920,1900-2018

this doesn't:
https://openhistoricalmap.github.io/openhistoricaltiles/leaflet-control-mbgltimeslider/demo/#10.000/50.31039/2.59758/1920,1900-2018

![Xc8F12W44m](https://user-images.githubusercontent.com/1423200/67305486-3e65fe00-f4aa-11e9-9281-e94e8cf496bb.gif)

Looking closer, it appears to be some issue with maptiles missing, though at first I thought it might be gaps in our stylesheet (like z levels inadvertently left out), but that doesn't appear to be the case as here:
![image](https://user-images.githubusercontent.com/1423200/67336519-581f3980-f4da-11e9-9918-8ac0b8ce424c.png)

Hmm, I wonder if this is a persisting issue with the sprite, though @tsinn pushed some fixes for that. Errors in console related to sprite and FontAwesome,
![image](https://user-images.githubusercontent.com/1423200/67336703-a9c7c400-f4da-11e9-8cff-96f6f2ddf22a.png)

**Comment by danrademacher** [comment]
@tsinn can you take a look at this? Might need Gregor's help, but first wondering if you can verify that the sprite is working or not working, so we can isolate that if it is the source of these errors.

**Comment by tsinn** [comment]
Thanks for the pointing to the errors in the Console. This led me to the answer. Villages were given a label text font of `Noto Sans` which is not available in the application. Changing to `Noto Sans Regular` which is available, fixed the rendering problems.
