### ISSUE TITLE
Data / Carto issue: Great Lakes vanish at z6+

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#7]
Starting view:  http://localhost:9000/#5.50/43.13520/-78.17927/

Zoom in a notch more, and see that it changes from z5 to z6 and cartography makes a transition.

Unfortunately part of this transition is that the Great Lakes vanish!

Same here, with some Canadian lakes slightly northeast in Quebec / Ontario:   http://localhost:9000/#5.97/49.53909/-74.88084/

Something in the SQL queries is filtering these out? The change happens at exactly *6.00* so I'm guessing a query, as opposed to a vector tile rendering glitch.

**Comment by gregallensworth** [comment]
Chosen as an example **Lake Michigan** since it's big enough to be visible and to have hover/click fx at z3.5. Confirmed that Lake Michigan is easily found in the DB at those far-out Zs, but is indeed absent at 6, 7, 8...

```
select COUNT(*) from water_z2 where name='Lake Michigan';
select COUNT(*) from water_z3 where name='Lake Michigan';
select COUNT(*) from water_z4 where name='Lake Michigan';
select COUNT(*) from water_z5 where name='Lake Michigan';
1

select COUNT(*) from water_z6 where name='Lake Michigan';
0
```

The non-ocean water features in the above tables, were loaded from **ne_50m_lakes** and **ne_10m_lakes**

At z7+ it changes to a completely different set of tables: *osm_water_polygon_gen5*, then 4, 3, 2, 1; then finally to *osm_water_polygon* at z12+

Therefore this is clearly something in the data-loading process and/or the starting datasets, that causes these features to be left out of *osm_water_polygon_gen5* et al, and from *osm_water_polygon*

**Comment by rwarren2** [comment]
I demand that you Make The Great Lakes Great Again!

**Comment by gregallensworth** [comment]
Turns out that the 10m is the best that Natural Earth has to offer, so we just have to roll with that. I have adjusted the `dbmods-water.sql` file so that the * ne_10m_lakes* table is added into the deeper *water_zX* tables.

This does work around the issue: the great lakes, etc. remain visible. However, see below for a few areas where the data conflict with other waterbody data. It's not very much, though, and is better than a whole inland sea vanishing!

![image](https://user-images.githubusercontent.com/3117633/42767871-eba0bcee-88d2-11e8-8f98-a9e646ea8abb.png)

**Comment by gregallensworth** [comment]
But... This does raise a larger question:

These waterbody data are not OSM/OHM at all, but NaturalEarth. They are not managed by any OSM/OHM process, but are "patched in" to a view so as to make for a more complete basemap. If the goal here is 100% pure OSM/OHM with start/end date information and managed via OSM/OHM processes... perhaps its inclusion is a bad idea, bound to cause confusion when folks try to edit it?

**Comment by rwarren2** [comment]
Not necessarily, [OpenSeaMap](https://en.wikipedia.org/wiki/OpenSeaMap) still uses the OSM base waterways even when there are differences. 

Having a vector representation of waterways globally is a serious amount of work just for current data. My thinking is that we go for the basics and then revisit the issue as more and more data is inserted into OHM.

**Comment by timwaters** [comment]
One would imagine the lakes/estuaries/coastlines changing shape over time. At the very least some of the areas by cities should see most change - The Manhattan coastline being a great example (http://maps.nypl.org/warper/maps/28440#Preview_tab)  Using current day coastlines would not lead to "map floodings" in the majority of cases :droplet: 

From what I recall there is a process for making coastlines from OSM data which is used in renderd in conjunction with natural earth  (NE data used for lower zooms). I'm not sure if any map servers use live coastline data, but they might do at high zooms?

**Comment by jeffreyameyer** [comment]
Does OSM really only use NE for zoom <= 6? I thought it was used at least at 8, but regardless...

The answer is that we should get the shoreline data into OHM. I tried double-checking this, but it appears that OHM is still down? @rwarren2 - is that right? I can take care of fixing that in the source later.

Agreed with @timwaters - we'll want to be able to show anthropomorphic change later.

@gregallensworth - would adding the data later be ok for now? If we have other waterway data, I suggest we solve this issue later.

**Comment by rwarren2** [comment]
OHM is using the basic mapnik hardcoded shortlines.  Lots of heavy sysadmin being done, will be worth it. I keep OpenHistoricalMap/ohm-website#27 updated with news.

**Comment by gregallensworth** [comment]
Per discussion earlier today: *Remove any usage of NaturalEarth data where `z >= 6`*

This does mean that the Great Lakes will vanish again, until such time as someone draws them into OHM. This has been acknowledged and chosen as the preferable behavior

**Comment by gregallensworth** [comment]
Done. At **z6+** only OSM/OHM data are used, no NaturalEarth.
